#!/bin/bash

PREV=prev-sh
NEXT=next-sh

python3 email-best.py > $NEXT

CMD=$(cmp --silent -- "$PREV" "$NEXT")

if [ "$?" -ne 0 ]; then
  TO='bostwickbrian@gmail.com,5166374271@vtext.com' #,ogiewan@optonline.net'
  SUBJECT="Free Games"
  GAMES=$(cat $NEXT)

  echo "$GAMES" | mail -s "$SUBJECT" $TO

  cp $NEXT $PREV
fi
